import Footer from "@/components/layout-components/root-layout/Footer";
import Header from "@/components/layout-components/root-layout/Header";
import type { Metadata } from "next";
import { Lemon, Mulish } from "next/font/google";
import "../globals.css";

const mulish = Mulish({ subsets: ["latin"] });
const lemon = Lemon({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
